### ISSUE TITLE
Array.from with readonlySets does not work

### ISSUE THREAD

**Issue by AidenFaulconer** [agiledigital/readonly-types#493]
Given the eslint configuration rule for _eslint-disable total-functions/no-unsafe-readonly-mutable-assignment_ 
```
const arrayFromSet: readonly ReadonlySet<number>[] = [
  readonlySet([0, 1, 2]),
] as const; //works
const arrayFromSet2: readonly ReadonlySet<number>[] = Array.From(
  readonlySet([0, 1, 2])
) as const; //fails
```

I can use the readonly set in an array, however I cannot create an array from the readonly set

**Comment by danielnixon** [comment]
`ReadonlySet` is a type built into TypeScript, it's not something provided by this library.

At first glance it sounds like the `eslint-plugin-total-functions` package should whitelist `Array.from`, because even though it takes a mutable parameter, passing a readonly argument is nevertheless safe - the readonly argument (in this case, a readonly set) cannot be mutated because `Array.from` always takes a shallow copy of its argument.

That would be equivalent to https://github.com/danielnixon/eslint-plugin-total-functions/issues/476.

Closing this issue because https://github.com/danielnixon/eslint-plugin-total-functions is the proper place to address.
